name: OrangeFox - 编译

# 致谢：
# https://github.com/TeamWin
# https://gitlab.com/OrangeFox
# https://github.com/azwhikaru（恢复分区编译模板）
# 以及所有相关仓库的贡献者

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OrangeFox 清单分支'
        required: true
        default: '12.1'
        type: choice
        options:
        - 12.1
        - 11.0
      DEVICE_TREE:
        description: 'OrangeFox 设备树'
        required: true
        default: 'https://github.com/OnePlus12R-development/android_device_oneplus_aston'
      DEVICE_TREE_BRANCH:
        description: 'OrangeFox 设备树分支'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: '指定设备路径'
        required: true
        default: 'device/oneplus/aston'
      DEVICE_NAME:
        description: '指定设备代号'
        required: true
        default: 'aston'
      BUILD_TARGET:
        description: '指定编译目标'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    name: 由 ${{ github.actor }} 编译 OrangeFox
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FOX_DIR: ${{ github.workspace }}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
    permissions:
      contents: write  # 只保留这一行，删除 artifacts: write
    steps:
    - name: 拉取仓库代码
      uses: actions/checkout@v4
              
    - name: 清理系统空间
      uses: rokibhasansagar/slimhub_actions@main

    - name: 配置交换空间
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: 搭建编译环境
      run: |
        sudo apt update && sudo apt install -y \
          aria2 \
          openjdk-11-jdk \
          python2 \
          ccache \
          lib32z1-dev \
          libncurses5-dev \
          squashfs-tools \
          xsltproc
        sudo ln -s /usr/bin/python2 /usr/bin/python
        git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
        cd scripts
        sudo bash setup/android_build_env.sh
        echo "编译环境搭建完成"
      
    - name: 同步OrangeFox源码
      run: |
        mkdir -p ${{ github.workspace }}/OrangeFox
        cd ${{ github.workspace }}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone https://gitlab.com/OrangeFox/sync.git -b master
        cd sync
        ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path $FOX_DIR --force
        if [ ! -d "$FOX_DIR" ]; then
          echo "错误：源码同步失败，未找到目录 $FOX_DIR"
          exit 1
        fi
        echo "OrangeFox源码已同步至 $FOX_DIR"

    - name: 克隆设备树
      run: |
        if [ ! -d "$FOX_DIR" ]; then
          echo "错误：源码目录 $FOX_DIR 不存在，同步步骤失败"
          exit 1
        fi
        cd $FOX_DIR
        mkdir -p $(dirname "${{ inputs.DEVICE_PATH }}")
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        if [ ! -d "./${{ inputs.DEVICE_PATH }}" ]; then
          echo "错误：设备树克隆失败，路径 ${{ inputs.DEVICE_PATH }} 不存在"
          exit 1
        fi
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "设备树克隆完成，提交ID：${{ env.COMMIT_ID }}"

    - name: 编译OrangeFox
      run: |
        if [ ! -d "$FOX_DIR" ]; then
          echo "错误：源码目录 $FOX_DIR 不存在"
          exit 1
        fi
        cd $FOX_DIR
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=${{ inputs.DEVICE_NAME }}
        echo "开始编译OrangeFox，目标设备：${{ inputs.DEVICE_NAME }}"
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make clean && mka -j$(nproc) adbd ${{ inputs.BUILD_TARGET }}image
        echo "编译完成"

    - name: 配置发布信息
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
        cd $FOX_DIR
        DEVICE_TREE_URL="${{ inputs.DEVICE_TREE }}"
        if [[ "$DEVICE_TREE_URL" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV
        echo "发布信息配置完成"

    - name: 上传编译产物到Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          $FOX_DIR/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.img
          $FOX_DIR/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: OrangeFox Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## OrangeFox Recovery 非官方编译
          编译分支：fox_${{ inputs.MANIFEST_BRANCH }}
          设备树：[设备树/分支](${{ env.DEVICE_TREE_URL }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          提交记录：最新 [提交](${{ env.DEVICE_TREE_URL }}/commit/${{ env.COMMIT_ID }})

    - name: 编译失败时收集日志
      if: failure()
      run: |
        echo "===== 同步日志 =====" > error_logs.txt
        cat ${{ github.workspace }}/OrangeFox/sync/sync.log >> error_logs.txt 2>&1
        echo -e "\n\n===== 编译日志 =====" >> error_logs.txt
        cat $FOX_DIR/out/build.log >> error_logs.txt 2>&1
        echo "错误日志已收集"

    - name: 上传错误日志
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 错误日志
        path: error_logs.txt
        retention-days: 7
