name: 橙狐（OrangeFox）- 构建

# 鸣谢：
# https://github.com/TeamWin
# https://gitlab.com/OrangeFox
# https://github.com/azwhikaru（恢复构建模板）
# 以及所有我使用过的仓库的贡献者

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: '橙狐清单分支'
        required: true
        default: '12.1'
        type: choice
        options:
        - 12.1
        - 11.0
      DEVICE_TREE:
        description: '橙狐设备树'
        required: true
        default: 'https://github.com/Tiansuoha/android_device_oneplus_aston'
      DEVICE_TREE_BRANCH:
        description: '橙狐设备树分支'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: '指定你的设备路径'
        required: true
        default: 'device/oplus/aston'
      DEVICE_NAME:
        description: '指定你的设备代号'
        required: true
        default: 'aston'
      BUILD_TARGET:
        description: '指定你的构建目标'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    name: 由 ${{ github.actor }} 构建橙狐恢复（OFR）
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
              
    - name: 清理环境
      uses: rokibhasansagar/slimhub_actions@main

    - name: 配置交换空间
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: 搭建构建环境
      run: |
        sudo apt install aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts.git -b master
        cd scripts
        sudo bash setup/android_build_env.sh
      
    - name: 配置清单文件
      if: inputs.MANIFEST_BRANCH == '11.0' || inputs.MANIFEST_BRANCH == '12.1'
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone https://gitlab.com/OrangeFox/sync.git -b master
        cd sync
        ./orangefox_sync.sh --branch ${{ inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}

    - name: 克隆设备树
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: 构建橙狐恢复
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image

    - name: 设置发布属性
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +%Y%m%d)" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}

        DEVICE_TREE_URL="${{ inputs.DEVICE_TREE }}"
        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV

    - name: 上传至发布
      uses: softprops/action-gh-release@v2
      with:
        files: |
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: 橙狐恢复 for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## 橙狐恢复构建 - 非官方
          构建版本: fox_${{ inputs.MANIFEST_BRANCH }}
          设备: [设备树/分支](${{ env.DEVICE_TREE_URL }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          提交: 构建时的最新[提交](${{ env.DEVICE_TREE_URL }}/commit/${{ env.COMMIT_ID }})。
